// <auto-generated />
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241031174356_DataSeeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Dog", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<int>("Tail_length")
                        .HasColumnType("int")
                        .HasColumnName("tail_length");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Name");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Name = "Max",
                            Color = "black",
                            Tail_length = 25,
                            Weight = 40
                        },
                        new
                        {
                            Name = "Lucy",
                            Color = "white",
                            Tail_length = 22,
                            Weight = 28
                        },
                        new
                        {
                            Name = "Rocky",
                            Color = "gray",
                            Tail_length = 24,
                            Weight = 35
                        },
                        new
                        {
                            Name = "Charlie",
                            Color = "red",
                            Tail_length = 29,
                            Weight = 32
                        },
                        new
                        {
                            Name = "Jack",
                            Color = "blue",
                            Tail_length = 21,
                            Weight = 29
                        },
                        new
                        {
                            Name = "Lola",
                            Color = "fawn",
                            Tail_length = 19,
                            Weight = 27
                        },
                        new
                        {
                            Name = "Roxy",
                            Color = "brindle",
                            Tail_length = 20,
                            Weight = 34
                        },
                        new
                        {
                            Name = "Bear",
                            Color = "tan",
                            Tail_length = 26,
                            Weight = 33
                        },
                        new
                        {
                            Name = "Ginger",
                            Color = "cream",
                            Tail_length = 18,
                            Weight = 24
                        },
                        new
                        {
                            Name = "Ruby",
                            Color = "apricot",
                            Tail_length = 24,
                            Weight = 30
                        },
                        new
                        {
                            Name = "Nala",
                            Color = "chestnut",
                            Tail_length = 19,
                            Weight = 28
                        },
                        new
                        {
                            Name = "Finn",
                            Color = "black&white",
                            Tail_length = 25,
                            Weight = 37
                        },
                        new
                        {
                            Name = "Sadie",
                            Color = "ivory",
                            Tail_length = 28,
                            Weight = 25
                        },
                        new
                        {
                            Name = "Jasper",
                            Color = "gray",
                            Tail_length = 23,
                            Weight = 30
                        },
                        new
                        {
                            Name = "Thor",
                            Color = "brown",
                            Tail_length = 27,
                            Weight = 30
                        },
                        new
                        {
                            Name = "Maggie",
                            Color = "black",
                            Tail_length = 20,
                            Weight = 32
                        },
                        new
                        {
                            Name = "Oscar",
                            Color = "chocolate",
                            Tail_length = 26,
                            Weight = 26
                        },
                        new
                        {
                            Name = "Bella",
                            Color = "golden",
                            Tail_length = 26,
                            Weight = 31
                        },
                        new
                        {
                            Name = "Penny",
                            Color = "fawn",
                            Tail_length = 22,
                            Weight = 30
                        },
                        new
                        {
                            Name = "Winston",
                            Color = "rust",
                            Tail_length = 19,
                            Weight = 28
                        },
                        new
                        {
                            Name = "Rex",
                            Color = "graphite",
                            Tail_length = 27,
                            Weight = 38
                        },
                        new
                        {
                            Name = "Ellie",
                            Color = "golden&white",
                            Tail_length = 30,
                            Weight = 29
                        },
                        new
                        {
                            Name = "Marley",
                            Color = "black&tan",
                            Tail_length = 20,
                            Weight = 31
                        },
                        new
                        {
                            Name = "Chance",
                            Color = "brown",
                            Tail_length = 21,
                            Weight = 33
                        },
                        new
                        {
                            Name = "Lucky",
                            Color = "tan",
                            Tail_length = 22,
                            Weight = 25
                        },
                        new
                        {
                            Name = "Baxter",
                            Color = "gray",
                            Tail_length = 24,
                            Weight = 39
                        },
                        new
                        {
                            Name = "Ember",
                            Color = "brown",
                            Tail_length = 20,
                            Weight = 32
                        },
                        new
                        {
                            Name = "Ollie",
                            Color = "black",
                            Tail_length = 19,
                            Weight = 30
                        },
                        new
                        {
                            Name = "Simba",
                            Color = "brown&white",
                            Tail_length = 21,
                            Weight = 36
                        },
                        new
                        {
                            Name = "Tina",
                            Color = "white",
                            Tail_length = 26,
                            Weight = 28
                        },
                        new
                        {
                            Name = "Stella",
                            Color = "golden",
                            Tail_length = 23,
                            Weight = 31
                        },
                        new
                        {
                            Name = "Blue",
                            Color = "blue",
                            Tail_length = 20,
                            Weight = 33
                        },
                        new
                        {
                            Name = "Beau",
                            Color = "red",
                            Tail_length = 29,
                            Weight = 29
                        },
                        new
                        {
                            Name = "Gizmo",
                            Color = "tan",
                            Tail_length = 26,
                            Weight = 32
                        },
                        new
                        {
                            Name = "Milo",
                            Color = "black&white",
                            Tail_length = 27,
                            Weight = 38
                        },
                        new
                        {
                            Name = "Koda",
                            Color = "chocolate",
                            Tail_length = 25,
                            Weight = 36
                        },
                        new
                        {
                            Name = "Ryder",
                            Color = "brown",
                            Tail_length = 30,
                            Weight = 37
                        },
                        new
                        {
                            Name = "Fido",
                            Color = "tan",
                            Tail_length = 22,
                            Weight = 28
                        },
                        new
                        {
                            Name = "Yuki",
                            Color = "golden&white",
                            Tail_length = 24,
                            Weight = 31
                        },
                        new
                        {
                            Name = "Dobby",
                            Color = "black",
                            Tail_length = 21,
                            Weight = 29
                        },
                        new
                        {
                            Name = "Gus",
                            Color = "gray",
                            Tail_length = 26,
                            Weight = 32
                        },
                        new
                        {
                            Name = "Mimi",
                            Color = "brown",
                            Tail_length = 20,
                            Weight = 28
                        },
                        new
                        {
                            Name = "Sammy",
                            Color = "brown",
                            Tail_length = 28,
                            Weight = 35
                        },
                        new
                        {
                            Name = "Scout",
                            Color = "golden",
                            Tail_length = 23,
                            Weight = 30
                        },
                        new
                        {
                            Name = "Angel",
                            Color = "cream",
                            Tail_length = 19,
                            Weight = 27
                        },
                        new
                        {
                            Name = "Holly",
                            Color = "fawn",
                            Tail_length = 22,
                            Weight = 34
                        },
                        new
                        {
                            Name = "Niko",
                            Color = "black",
                            Tail_length = 25,
                            Weight = 29
                        },
                        new
                        {
                            Name = "Dash",
                            Color = "tan",
                            Tail_length = 21,
                            Weight = 31
                        },
                        new
                        {
                            Name = "Rocco",
                            Color = "brown&white",
                            Tail_length = 24,
                            Weight = 36
                        },
                        new
                        {
                            Name = "Ella",
                            Color = "cream",
                            Tail_length = 19,
                            Weight = 30
                        },
                        new
                        {
                            Name = "Benny",
                            Color = "black",
                            Tail_length = 30,
                            Weight = 30
                        },
                        new
                        {
                            Name = "Teddy",
                            Color = "gray",
                            Tail_length = 27,
                            Weight = 38
                        },
                        new
                        {
                            Name = "Chester",
                            Color = "brown",
                            Tail_length = 19,
                            Weight = 28
                        },
                        new
                        {
                            Name = "Cleo",
                            Color = "golden",
                            Tail_length = 26,
                            Weight = 32
                        },
                        new
                        {
                            Name = "Ruff",
                            Color = "brown",
                            Tail_length = 25,
                            Weight = 35
                        },
                        new
                        {
                            Name = "Whiskey",
                            Color = "gray",
                            Tail_length = 23,
                            Weight = 27
                        },
                        new
                        {
                            Name = "Bruno",
                            Color = "brown&white",
                            Tail_length = 24,
                            Weight = 31
                        },
                        new
                        {
                            Name = "Tango",
                            Color = "tan",
                            Tail_length = 22,
                            Weight = 29
                        },
                        new
                        {
                            Name = "Biscuit",
                            Color = "golden",
                            Tail_length = 21,
                            Weight = 30
                        },
                        new
                        {
                            Name = "Amber",
                            Color = "brown",
                            Tail_length = 26,
                            Weight = 28
                        },
                        new
                        {
                            Name = "Pepper",
                            Color = "gray",
                            Tail_length = 22,
                            Weight = 33
                        },
                        new
                        {
                            Name = "Sasha",
                            Color = "black",
                            Tail_length = 24,
                            Weight = 35
                        },
                        new
                        {
                            Name = "Buster",
                            Color = "tan",
                            Tail_length = 20,
                            Weight = 31
                        },
                        new
                        {
                            Name = "Nina",
                            Color = "brown&white",
                            Tail_length = 28,
                            Weight = 29
                        },
                        new
                        {
                            Name = "Piper",
                            Color = "golden&white",
                            Tail_length = 25,
                            Weight = 32
                        },
                        new
                        {
                            Name = "Kira",
                            Color = "red",
                            Tail_length = 19,
                            Weight = 30
                        },
                        new
                        {
                            Name = "Rusty",
                            Color = "black&tan",
                            Tail_length = 23,
                            Weight = 36
                        },
                        new
                        {
                            Name = "Luna",
                            Color = "chocolate",
                            Tail_length = 22,
                            Weight = 30
                        },
                        new
                        {
                            Name = "Chloe",
                            Color = "brindle",
                            Tail_length = 20,
                            Weight = 34
                        },
                        new
                        {
                            Name = "Sunny",
                            Color = "fawn",
                            Tail_length = 25,
                            Weight = 29
                        },
                        new
                        {
                            Name = "Misty",
                            Color = "ivory",
                            Tail_length = 21,
                            Weight = 32
                        },
                        new
                        {
                            Name = "Duke",
                            Color = "chestnut",
                            Tail_length = 24,
                            Weight = 33
                        },
                        new
                        {
                            Name = "Snow",
                            Color = "white",
                            Tail_length = 27,
                            Weight = 36
                        },
                        new
                        {
                            Name = "Coco",
                            Color = "brown",
                            Tail_length = 28,
                            Weight = 31
                        },
                        new
                        {
                            Name = "Daisy",
                            Color = "golden",
                            Tail_length = 19,
                            Weight = 30
                        },
                        new
                        {
                            Name = "Buddy",
                            Color = "black&white",
                            Tail_length = 23,
                            Weight = 32
                        },
                        new
                        {
                            Name = "Cindy",
                            Color = "tan",
                            Tail_length = 22,
                            Weight = 29
                        },
                        new
                        {
                            Name = "Toby",
                            Color = "gray",
                            Tail_length = 24,
                            Weight = 35
                        },
                        new
                        {
                            Name = "Zoey",
                            Color = "golden&white",
                            Tail_length = 25,
                            Weight = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
