@Api = http://localhost:5275

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Jessy",
  "color": "black&white",
  "tail_length": 7,
  "weight": 14
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Buddy",
  "color": "brown",
  "tail_length": 12,
  "weight": 20
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Molly",
  "color": "black",
  "tail_length": 9,
  "weight": 15
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Charlie",
  "color": "white",
  "tail_length": 11,
  "weight": 18
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Lucy",
  "color": "golden",
  "tail_length": 10,
  "weight": 22
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Max",
  "color": "grey",
  "tail_length": 8,
  "weight": 14
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Bailey",
  "color": "brown",
  "tail_length": 15,
  "weight": 24
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Luna",
  "color": "black&white",
  "tail_length": 7,
  "weight": 13
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Cooper",
  "color": "tan",
  "tail_length": 10,
  "weight": 19
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Daisy",
  "color": "spotted",
  "tail_length": 9,
  "weight": 17
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Rocky",
  "color": "black",
  "tail_length": 12,
  "weight": 21
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Maggie",
  "color": "white",
  "tail_length": 8,
  "weight": 15
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Rex",
  "color": "grey",
  "tail_length": 14,
  "weight": 25
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Bella",
  "color": "golden",
  "tail_length": 11,
  "weight": 16
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Oscar",
  "color": "spotted",
  "tail_length": 9,
  "weight": 18
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Rosie",
  "color": "tan",
  "tail_length": 10,
  "weight": 20
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Ruby",
  "color": "white",
  "tail_length": 8,
  "weight": 15
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Shadow",
  "color": "black",
  "tail_length": 13,
  "weight": 22
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Harley",
  "color": "grey",
  "tail_length": 11,
  "weight": 19
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Milo",
  "color": "brown",
  "tail_length": 10,
  "weight": 17
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Lily",
  "color": "black&white",
  "tail_length": 7,
  "weight": 13
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Ranger",
  "color": "golden",
  "tail_length": 10,
  "weight": 21
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Sadie",
  "color": "spotted",
  "tail_length": 8,
  "weight": 15
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Finn",
  "color": "white",
  "tail_length": 12,
  "weight": 23
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Holly",
  "color": "tan",
  "tail_length": 9,
  "weight": 17
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Bandit",
  "color": "brown",
  "tail_length": 11,
  "weight": 20
}

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Leo",
  "color": "grey",
  "tail_length": 35,
  "weight": 26
}

