@Api = http://localhost:5275

GET {{Api}}/ping/
Accept: application/json

###

GET {{Api}}/dogs/
Accept: application/json

###

GET {{Api}}/dogs?pageNumber=3&pageSize=10
Accept: application/json

###

GET {{Api}}/dogs?attribute=color&order=desc
Accept: application/json

###

GET {{Api}}/dogs?attribute=color&order=desc&pageNumber=3&pageSize=10
Accept: application/json

###