@Api = http://localhost:5275

GET {{Api}}/ping/
Accept: application/json

###

POST {{Api}}/dog
Content-Type: application/json

{
  "name": "Leo",
  "color": "grey",
  "tail_length": 35,
  "weight": 26
}

###

GET {{Api}}/dogs/
Accept: application/json

###

GET {{Api}}/dogs?pageNumber=2&pageSize=10
Accept: application/json

###

GET {{Api}}/dogs?attribute=color&order=desc
Accept: application/json

###

GET {{Api}}/dogs?attribute=color&order=desc&pageNumber=2&pageSize=10
Accept: application/json

###